# Copyright 2021 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

[GLOBAL]
pants_version = "2.14.0"
backend_packages = ["pants.backend.experimental.go"]

[golang]
minimum_expected_version = "1.18"

[test]
extra_env_vars = [
    "GOCACHE",
    "HOME"
]